task:
  only_if: $CIRRUS_BRANCH == 'master' || $CIRRUS_PR != ''
  matrix:
    - name: FreeBSD 13.2
      freebsd_instance:
        image_family: freebsd-13-2-snap
 # Install Rust
  setup_script:
    - fetch https://sh.rustup.rs -o rustup.sh
    - sh rustup.sh -y --profile=minimal --default-toolchain stable
    - pkg install -y cmake fontconfig pkgconf libxkbcommon
  test_script:
    - . $HOME/.cargo/env
    - mkdir -p $HOME/sockets
    - export XDG_RUNTIME_DIR="$HOME/sockets"
    - cargo test
